/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    BaseGenerator: typeof import('./src/components/generators/BaseGenerator.vue')['default']
    BaseValidator: typeof import('./src/components/validators/BaseValidator.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    CPF: typeof import('./src/components/generators/GenerateCPF.vue')['default']
    Documents: typeof import('./src/components/generators/BaseGenerator.vue')['default']
    GenerateCPF: typeof import('./src/components/generators/GenerateCPF.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    SuccessShapeButton: typeof import('./src/components/buttons/SuccessShapeButton.vue')['default']
    ValidateCPF: typeof import('./src/components/validators/ValidateCPF.vue')['default']
  }
}
